# Questions 10-13 of SQL Case Study

In [1]:
#Import and define functions
import sqlite3
from sqlite3 import Error
 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

## QUESTION 10:
Produce a list of facilities with a total revenue less than 1000.
The output of facility name and total revenue, sorted by revenue. Remember
that there's a different cost for guests and members!

In [21]:
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT
            f.name,
            CASE WHEN b.memid = 0 THEN SUM(b.slots*f.guestcost) 
                WHEN b.memid > 0 THEN SUM(b.slots*f.membercost)
                ELSE 'Else'
                END AS session_cost
        FROM Bookings AS b
        LEFT JOIN Facilities AS f
            ON b.facid = f.facid
        GROUP BY f.name
            HAVING session_cost > 1000
        ORDER BY session_cost DESC
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite-db-pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Tennis Court 2', 31950)
('Squash Court', 19320.0)
('Massage Room 2', 18240)
('Massage Room 1', 13899.599999999893)
('Tennis Court 1', 6600)

## QUESTION 11:
Produce a report of members and who recommended them in alphabetic surname,firstname order.

In [ ]:
import sqlite3
from sqlite3 import Error
 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn
 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT
            m1.firstname,
            m1.surname,
            CASE WHEN m2.memid = 0 THEN 'NULL'
                WHEN m2.memid != 0 THEN CONCAT(m2.firstname, ' ', m2.surname) 
                END AS 'Recommended By'
        FROM Members AS m1
        LEFT JOIN Members AS m2
            ON m1.recommendedby = m2.memid
        WHERE m1.memid > 0
        ORDER BY m1.surname
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite-db-pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

## QUESTION 12:
Find the facilities with their usage by member, but not guests

In [23]:
import sqlite3
from sqlite3 import Error
 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn
 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT
            f.name,
            SUM(b.slots)
        FROM Bookings AS b
        LEFT JOIN Facilities AS f
            ON f.facid = b.facid
        LEFT JOIN Members AS m
            ON m.memid = b.memid
        WHERE b.memid != 0
        GROUP BY f.name
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite-db-pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Badminton Court', 1086)
('Massage Room 1', 884)
('Massage Room 2', 54)
('Pool Table', 856)
('Snooker Table', 860)
('Squash Court', 418)
('Table Tennis', 794)
('Tennis Court 1', 957)
('Tennis Court 2', 882)

## QUESTION 13:
Find the facilities usage by month, but not guests.

In [4]:
import sqlite3
from sqlite3 import Error
 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn
 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT
            strftime('%m', starttime) AS 'month',
            f.name,
            SUM(slots)
        FROM Bookings AS b
        LEFT JOIN Facilities AS f
            ON f.facid = b.facid
        WHERE b.memid != 0
        GROUP BY (month), f.name
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite-db-pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('07', 'Badminton Court', 165)
('07', 'Massage Room 1', 166)
('07', 'Massage Room 2', 8)
('07', 'Pool Table', 110)
('07', 'Snooker Table', 140)
('07', 'Squash Court', 50)
('07', 'Table Tennis', 98)
('07', 'Tennis Court 1', 201)
('07', 'Tennis Court 2', 123)
('08', 'Badminton Court', 414)
('08', 'Massage Room 1', 316)
('08', 'Massage Room 2', 18)
('08', 'Pool Table', 303)
('08', 'Snooker Table', 316)
('08', 'Squash Court', 184)
('08', 'Table Tennis', 296)
('08', 'Tennis Court 1', 339)
('08', 'Tennis Court 2', 345)
('09', 'Badminton Court', 507)
('09', 'Massage Room 1', 402)
('09', 'Massage Room 2', 28)
('09', 'Pool Table', 443)
('09', 'Snooker Table', 404)
('09', 'Squash Court', 184)
('09', 'Table Tennis', 400)
('09', 'Tennis Court 1', 417)
('09', 'Tennis Court 2', 414)